CUDA_VISIBLE_DEVICES=0 python supervised_finetuning.py \
    --model_name_or_path ./model/Qwen2.5b-3B-Instruct \
    --train_file_dir ./mydata/medical/finetune/precessed_train\
    --validation_file_dir ./mydata/medical/finetune/precessed_test\
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --do_train \
    --do_eval \
    --template_name qwen \
    --use_peft True \
    --max_train_samples -1 \
    --max_eval_samples 50 \
    --model_max_length 4096 \
    --num_train_epochs 2 \
    --learning_rate 5e-5 \
    --warmup_ratio 0.05 \
    --weight_decay 0.05 \
    --logging_strategy steps \
    --logging_steps 20 \
    --eval_steps 1000 \
    --eval_strategy steps \
    --save_steps 1000 \
    --save_strategy steps \
    --save_total_limit 10 \
    --gradient_accumulation_steps 4 \
    --preprocessing_num_workers 8 \
    --output_dir outputs-sft-qwen2.5-v1 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype bfloat16 \
    --bf16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --cache_dir ./cache --flash_attn True
